Machine.add(me.dir()+"/BPM.ck");
Machine.add(me.dir()+"/player.ck");
Machine.add(me.dir()+"/secondrun.ck");
Machine.add(me.dir()+"/reminiscence.ck");
Machine.add(me.dir()+"/violin.ck");
Machine.add(me.dir()+"/viola.ck");
Machine.add(me.dir()+"/bass.ck");
Machine.add(me.dir()+"/contra.ck");
Machine.add(me.dir()+"/score.ck");